server:
  port: 8080

spring:
  application:
    name: soim
  # TEMPORARY: disable DB/JPA autoconfiguration until Postgres is ready
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
